### ISSUE TITLE
Bootstrapping from guile fails: "Unbound variable: %file-exists?"

### ISSUE THREAD

**Issue by cwebber** [google/schism#103]
When running `./bootstrap-from-guile.sh`

```
schism/compiler.ss:193:53: In procedure module-lookup: Unbound variable: %file-exists?
```

Looks like this bug was introduced in commit c6eda3d, which would make sense given the commit message.

**Comment by eholk** [comment]
Yikes, good catch! I should probably add Guile bootstrap to Travis so I don't accidentally check in issues like this in the future.

**Comment by cwebber** [comment]
Good call!  Hopefully now that this works maybe I can figure out how to use the project and maybe even become a productive contributor.  I love that schism exists and want it to succeed :D

**Comment by eholk** [comment]
Awesome! I'm happy to take your contributions. Please feel free to ask if you need help getting started, or want ideas for starter projects.

Is there an area you're interested in contributing to? Was there some project you were hoping to do using Schism?

**Comment by cwebber** [comment]
Right now I'm mostly interested in learning how WASM works.  In the long run, I'd like to see Scheme succeed in the browser, maybe through this or through Guile or Racket.  I'm not really sure where to get started with that... it would be nice if I felt like I could "play with" WASM in some way that felt intuitive, and since I know Scheme pretty well this felt like maybe a good place to do it.  (My main work is on secure, distributed social networks and actor model / object capability stuff... the kind of stuff Mark Miller and company work on, except I prefer a lispier approach than JS where possible.)

If you have recommendations on good places to get started in the codebase, let me know.  I plan to read the docs.  At the moment I'm not really sure what to do though.

Feel free to [contact me directly](https://dustycloud.org/contact/), especially over IRC or XMPP if you want to chat more (though email, or this thread, works too).

**Comment by cwebber** [comment]
By the way, we met a couple of years ago at TPAC.  If you remember an overly-enthusiastic onlooker who sat in on one of the WASM groups, got excited about you talking about Schism, and talked about their involvement in the Guile community, that was me. ;)

**Comment by eholk** [comment]
Oh yeah! I do remember that! Thanks for the contact info. I'll reach out there so we can avoid getting too far off topic in this thread.
