### ISSUE TITLE
master playground doesn't work

### ISSUE THREAD

**Issue by mohe2015** [google/schism#105]
I really like the idea of this project but I currently can't get it to run in the browser.

Running the master playground doesn't work: 
"Error: Scheme runtime error in char->integer: not a char"

Running `./bootstrap-from-guile.sh` didn't work either.
"Error: Scheme runtime error in read-library: Could not find library"

https://github.com/google/schism/pull/65 works.

It would be great if somebody could help me although I just wanted to try this project out and are not currently planning to actively use it.

**Comment by eholk** [comment]
Hey, sorry for taking so long the respond!

One issue with the playground currently is that Schism generates `return_call` instructions, which last I checked, browsers do not have enabled by default. This may have changed though.

At any rate, the issue you're hitting sounds like a different one. I think it may be some of the library changes we've made. We can load libraries from the file system, but we haven't put a fall back in place for running on the web.

**Comment by jitwit** [comment]
I was playing around with this today. I think I'm hitting an issue where what is failing is parsing `rnrs.ss`:
```
rt.js:110 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at eq? (rt.js:110)
    at char-whitespace? (wasm-function[490]:0x110aa)
    at char-symbolic? (wasm-function[509]:0x11404)
    at read-symbol (wasm-function[510]:0x11474)
    at read-symbol (wasm-function[510]:0x11483)
    at read-symbol (wasm-function[510]:0x11483)
    at read-symbol (wasm-function[510]:0x11483)
    at read-symbol (wasm-function[510]:0x11483)
    at read-symbol (wasm-function[510]:0x11483)
    at read-symbol (wasm-function[510]:0x11483)
```
I did manage to get a program to run from the playground by not importing it, though
