### ISSUE TITLE
More efficient string representation

### ISSUE THREAD

**Issue by eholk** [google/schism#38]
Strings right now are represented as lists of characters with a different tag. This is inefficient. We should use a better representation, such as a vector of characters. This should help some with #32.

**Comment by eholk** [comment]
I have a vector of characters version in a branch. I think all the tests are passing now, but weirdly it comes at a huge performance regression. I'll try again after @wingo's symbol table hashing change, and maybe that will reduce the performance impact (although I'd expect vector-of-chars to be faster than linked-list-of-chars, so if it's not actually a speed up we probably don't want to make the change).

**Comment by eholk** [comment]
See https://github.com/eholk/schism/tree/wip-string-representation for the current vector-of-chars progress. The current performance numbers are:

```
Compiling stage1 compiler...
  Time: 4.771 s

Compiling stage2 compiler...
  Time: 6.567 s

Compiling stage3 compiler...
  Time: 6.788 s

Percent change (1 -> 3): 42%
Percent change (2 -> 3): 3%
```

I'm guessing this is mainly due to a large code size increase.

**Comment by amirouche** [comment]
> Strings right now are represented as lists of characters with a different tag.

IIUC strings are now represented as strings with a `s` prefix.

https://github.com/google/schism/blob/b709b789b5164847caf94cdd823811cf6391bdb3/rt/rt.mjs#L53-L55

**Comment by eholk** [comment]
Ah, yes. The representation has changed since I wrote that comment :)

**Comment by eholk** [comment]
This is fixed now that all of our data are JavaScript objects.
