### ISSUE TITLE
First class procedures

### ISSUE THREAD

**Issue by amirouche** [google/schism#85]
Are first class procedures supported?

**Comment by amirouche** [comment]
Based on https://github.com/google/schism/issues/4 it seems like yes.

But reading the code, I can not tell.

**Comment by eholk** [comment]
Yes, they are. They are used pretty extensively within the compiler at this point.

Most of the code that implements them is around here: https://github.com/google/schism/blob/master/schism/compiler.ss#L1017

Is there something in particular that is not working for you?

**Comment by amirouche** [comment]
> Is there something in particular that is not working for you?

indeed it works.

Thanks for sharing!

**Comment by amirouche** [comment]
FWIW, I am working on Scheme to JavaScript compiler and I was wondering how to translate to wasm instead. [wasm2wat](https://github.com/webassembly/wabt) and the code of Schism help.

**Comment by eholk** [comment]
Great, I'm glad lambdas are working for you, and I hope Schism is a helpful reference. Good luck!
