### ISSUE TITLE
README.md review: What does Schism do?

### ISSUE THREAD

**Issue by AMDphreak** [google/schism#93]
Can someone add a lay-person explanation to the first paragraph to lighten the conceptual blow of the description? The reader needs to know Schism does. The "self-hosting compiler from a subset of R6RS Scheme to WebAssembly" is a wide conceptual gap and is opaque. What does "self-hosting compiler" mean? What is R6RS? (I know, but most readers won't). WebAssembly is still a very new tech. It may help to explain Schism and WASM in terms of "software", "server", "browser", and "deployment". I will update this recommendation if I have any new intuitions.

**Comment by eholk** [comment]
Thanks for the suggestion. It looks like parts of the README are a little stale, since it was written at the very beginning of the project.

What about something like this?

> Schism is an experimental compiler from Scheme to WebAssembly. It enables developers to run programs written in Scheme in the browser or server environments such as NodeJS. The compiler supports a subset of the R6RS version Scheme, and is self-hosting, meaning Schism is implemented in Schism itself.

**Comment by AMDphreak** [comment]
Pack her up boys, she's ready to go.
